### ISSUE TITLE
Goals

### ISSUE THREAD

**Issue by hokiespurs** [hokiespurs/uasortho#1]
V0
- [x] form input + slider (EO,IO,Appearance) 
- [x] draggable UAS
- [x] Handle Horizon and back projection

V1
- [x] [Sidebar](https://github.com/Turbo87/sidebar-v2)
- [x] Draggable center of Image to update Pitch/Yaw
- [x] Slider bar and form for input
- [x] Dropdown for various UAS
- [x] Custom Colors

V2
- [x] Compute GSD
- [x] Button to add multiple UAS 

V100
- [ ] Ortho uncertainty visualization
- [ ] Add GCPs
- [ ] Visualize how collinear they are in each dimension
- [ ] Example popup to show land/sky view
- [ ] Shareable Hyperlink (might be too hard for V1)

**Comment by hokiespurs** [comment]
- opted against scrollbar
- dropdown functionality enabled (not yet populated with many cameras)
- no button for multiple

**Comment by hokiespurs** [comment]
## Todo V1
- [ ] add custom colors for markers and footprint
- [ ] add grid-lines in footprint
- [ ] add location search bar on top
- [ ] add GSD computations
- [ ] add GSD colorbars
- [ ] add GSD min/max functionality
- [ ] add Help Tab Modal
- [ ] add About Tab Modal
- [ ] add Tools Dropdown
  - Zoom to Extent
  - Fly to Here

## Populate Fields
- [ ] populate with example cameras
- [ ] populate example EPSG projections
- [ ] populate example locations

## Document
- [ ] how to functionality of the site
- [ ] how to add new cameras, projections, and locations to js files

**Comment by hokiespurs** [comment]
- [ ] add "stamp" tool
  - click stamp to add the footprint and camera position permanently to the map
  - add popup so that when the polygon is clicked, a popup showing camera parameters pops up
  - add buttons to settings so when clicked, a popup showing parameters appears
  - add button to clear footprints
- [ ] add gsd grid to myCamera
- [ ] add functionality to auto-update
- [ ] add colormap to color the pixels
- [ ] make grid not go into horizon
- [ ] add grid line color, fill color, line weight, opacity
- [ ] add ngrid cells in Y dimension input
- [ ] add pixel size input

**Comment by hokiespurs** [comment]
- [ ] add "how-to" carousel
- [ ] add github documentation
  - how to populate example cameras
  - how to populate example EPSG projections
  - how to populate example locations
- [ ] add DJI cameras to cameras
- [ ] add caveat in documentation about accuracy of lens parameters
